spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

server:
  servlet:
    encoding:
      force: true

blog:
  title: Sanzio-Blog
  banner:
    title: Welcome
    content: Welcome to My first Kotlin Blog!